name: netflix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  lottie: ^3.1.3
  path_provider: ^2.1.5
  stroke_text: ^0.0.3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/netflix_intro_animation.json
    - assets/movie_posters/

fonts:
  - family: Netflix_Sans
    fonts:
      - asset: assets/fonts/Netflix_Sans_Bold.otf
        weight: 700
      - asset: assets/fonts/Netflix_Sans_Medium.otf
        weight: 500
      - asset: assets/fonts/Netflix_Sans_Light.otf
        weight: 300
